services:

  postgres:
    image: postgres:17

    container_name: gst-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: gst
      POSTGRES_PASSWORD: gst
      POSTGRES_DB: gst_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
